### ISSUE TITLE
Add destination field to encrypted Grinbox messages

### ISSUE THREAD

**Issue by jaspervdm** [vault713/wallet713#102]
This will strengthen transaction proofs

**Comment by ravidio** [comment]
@jaspervdm are you thinking of adding the 'from' field into the contents of the encrypted message? i.e. encrypting a struct that holds an address+slate? This will break protocol compatibility. The other option is to leave the encrypted_message only be the serialised slate, and add along-side a second encrypted string (using the same key) for the 'from' address.

**Comment by jaspervdm** [comment]
We could add an `Option<String>` field to the message, this will be compatible with old clients. Then, at the same time as the Grin hard fork, we could require all users to update their client and make the destination field mandatory.

**Comment by jaspervdm** [comment]
Solved with #110
