### ISSUE TITLE
Windows build possible?

### ISSUE THREAD

**Issue by cyberpunkbln** [vault713/wallet713#106]
Hello,
short question. Is a windows build possible in the near future?
thx

Edit: I see windows build are more than ncurse problems. Looks like the windows build problems must be solved in the grin-core first. Looks like cross compiling is the problemsolving at the moment.
Edit: Crosscompile don't functioned, he doesnt find the right open ssl libs.

**Comment by lehnberg** [comment]
@cyberpunkbln windows builds are now working FYI
