### ISSUE TITLE
Enable 443 to be used for multiple listeners?

### ISSUE THREAD

**Issue by lehnberg** [vault713/wallet713#116]
As an anonymous cryptocurrency creator looking to accept donations from users via both https and grinbox, I'd like to be able to run both my https and grinbox listener concurrently, so that I don't have to run two separate servers.

Not even sure this is possible, but relevant [Gitter chat log](
https://gitter.im/grin_community/Lobby?at=5c577f8d8aa5ca5abf7d3dd9):

> Ignotus Peverell @ignopeverell Feb 03 23:55
> might have to use a different server, the listener is already taking 443 on that one

**Comment by ignopeverell** [comment]
Not possible to run 2 servers on the same port. But given that you guys already embed a lot of grin wallet code, you could run the listener as part of wallet713 and sniff if the message coming in is for the grin listener or your own protocol and forward/process accordingly.

**Comment by lehnberg** [comment]
Okay so @ignopeverell after some discussion with @ravidio, no additional work is required for this, wallet713 supports running an https and grinbox listener from the same machine as is.

### Steps:
1. Run wallet713 only.
1. Enable Foreign API by editing `~/.wallet713/main/wallet713.toml` and including
   ```
   foreign_api=true
   foreign_api_address = "0.0.0.0:13415"
   ```
   where you specify IP:PORT bind. 
1. Configure your domain and https certs correctly.
1. Run wallet713, and that's it. You should now be listening on the IP assigned to you on the network. And if you set up DNS etc it can be accessible via a domain name.
1. To run grinbox listener, you either run `listen` inside the wallet or configure `wallet713.toml` to include `grinbox_listener_auto_start = true` in order for it to start automatically.

**Comment by lehnberg** [comment]
Also, just to clarify: The grinbox listener does not need an inbound port.
