### ISSUE TITLE
build from source ends with error

### ISSUE THREAD

**Issue by urza** [vault713/wallet713#118]
Following instructions on building from source resulted in this error:

```
:~/wallet713/wallet713$ cargo build --release
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/mimblewimble/grin`
error: no matching package named `grin_api` found
location searched: https://github.com/mimblewimble/grin#c41ea4bc
required by package `wallet713 v1.0.1 (file:///home/urza/wallet713/wallet713)`
```

**Comment by ravidio** [comment]
Hey @urza, not sure what this is about :) There's definitely a grin_api package in the grin repo (https://github.com/mimblewimble/grin/tree/master/api). Did it eventually work for you?

**Comment by urza** [comment]
Hi @ravidio , I didnt make any more attempts.. are there perhaps some rust commands that I may try? maybe something wrong in my rust/cargo cache? I was building grin a while back on this machine (that I since deleted and use grin binary releases). Sorry I am not at all familiar with rust ecosystem and how to properly use cargo :) just copy pasting commands from grin and wallet713 readmes :)

**Comment by jaspervdm** [comment]
Can we assume this is fixed? Latest master should build without problem. If you do still have issues, please re-open.
