### ISSUE TITLE
openssl issue with 1.0.1 (but not with 1.0.0) on macOS

### ISSUE THREAD

**Issue by mickaphd** [vault713/wallet713#128]
I used the binaries for the v.1.0.0 from the beginning. Works perfectly. But impossible to use the new version 1.0.1. as I have this message: 
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/me/Desktop/wallet713
  Reason: image not found
Abort trap: 6
I don't get it because I installed (and re-installed) with Brew openssl and the v.1.0.0 works perfectly.
Thanks for the help

**Comment by ravidio** [comment]
Hi @mickaphd, could you try the following: 

brew install openssl@1.1

You may need to restart the terminal once done, but that should install the required dependency.

**Comment by mickaphd** [comment]
Thanks much @ravidio it works perfectly. Feel stupid... but I didn't suspected that as I updated openssl with Brew but maybe not the 1.1. Whatever, thank you!
