### ISSUE TITLE
Refreshing wallet outputs produces very long URIs

### ISSUE THREAD

**Issue by NotMrPotter** [vault713/wallet713#164]
During output refreshes, wallet713 currently queries a Grin node up to 200 IDs at a time via. HTTP GET. This can be problematic with proxies or load balancers (i.e. nginx) in the mix, due to the extreme length of the query's URI.

If you're open to it, I would like to offer a small PR that restricts these queries down to a generally safe sub-8KB maximum.

**Comment by lehnberg** [comment]
Hi @NotMrPotter, thanks for flagging this and for offering to help! If you submit a PR for this fix in the near future, we'll merge it.

**Comment by jaspervdm** [comment]
Fixed in #165
