### ISSUE TITLE
beta2 crashes on windows after restoring wallet

### ISSUE THREAD

**Issue by DavidBurkett** [vault713/wallet713#174]
Running windows 10. Restored from seed. Took a couple minutes, and then crashed. Now when I open it, I enter my password, press enter, and it crashes. Can't find the logs, or I would attach them.

**Comment by jaspervdm** [comment]
Hm, that's weird. I just did a restore from a seed on Windows 10 and it worked without issue. To see logs, set environment variable `RUST_LOG` to `DEBUG` and run with `--daemon` flag

**Comment by DavidBurkett** [comment]
It was just using the old node. I double-clicked the exe, rather than running it from command prompt, so I didn't see the:
```
The Grin Node in use (version 1.x.x series) is outdated and incompatible with this wallet version.
Please update the node to version 2.0.0 or later and try again.
```
Pro-tip: For windows, it's recommended to do a system("pause"), or however it's done in rust, before terminating, unless the user specifically requested to quit.
