### ISSUE TITLE
Latest master fails to build with rust 1.38.0

### ISSUE THREAD

**Issue by schofieldn** [vault713/wallet713#182]
Following upgrade from rust 1.37.0 to 1.38.0, latest master fails to build with the following error and lots of warnings:

<snip>
   Compiling env_logger v0.6.1
   Compiling rustc_version v0.2.3
error: proc-macro derive panicked
  --> /home/neil/.cargo/registry/src/github.com-1ecc6299db9ec823/grin_secp256k1zkp-0.7.7/src/key.rs:32:10
   |
32 | #[derive(Zeroize)]
   |          ^^^^^^^
   |
   = help: message: unknown zeroize attribute: (drop)

error: aborting due to previous error

The following warnings were emitted during compilation:
<snip>

**Comment by jaspervdm** [comment]
Thanks for reporting, its fixed now. You will get some warning regarding missing `dyn` keywords but you can safely ignore them, they will be addressed in a future PR.
