### ISSUE TITLE
Support multiple networks

### ISSUE THREAD

**Issue by jaspervdm** [vault713/wallet713#19]
Soon floonet and mainnet will exist in parallel. We want to make sure wallets listening on one network are only able to send and receive to other wallets on the same chain. This can be done by using different version bytes for the grinbox addresses. When sending/receiving, the version bytes should be compared to the one corresponding to the current chain type.

**Comment by ravidio** [comment]
@jaspervdm what about keybase listeners? is there a solution that will work for both?

**Comment by jaspervdm** [comment]
Hm, I don't think so, unless we open a PR on Grin to add chain type directly in the slate
