### ISSUE TITLE
Panic running keybase listener

### ISSUE THREAD

**Issue by lehnberg** [vault713/wallet713#31]
from a user:
```
wallet713> listen --keybase starting keybase listener... 
wallet713> thread '<unnamed>' panicked at 'No output: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:1009:5 note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
what's that?
ravidio
10:33 AM
must be keybase app missing or something like that.
should be more graceful for sure.

**Comment by ravidio** [comment]
@lehnberg any more details on how to reproduce?

**Comment by lehnberg** [comment]
Was confirmed by user that they were not running keybase app on machine
