### ISSUE TITLE
Support issuing invoices  

### ISSUE THREAD

**Issue by lehnberg** [vault713/wallet713#4]
Related [forum thread](https://www.grin-forum.org/t/reverse-transaction-building/482)

Add support for the reversed flow of `send` command: a Payee/Receiver uses the `invoice` command to create a slate to receive a designated amount and passes this to the Payer/Sender that then processes and returns the slate to Payee who then finalises and broadcasts the transaction.

Useful in online merchant flows or for "requesting payments" of certain amounts.

**Comment by ravidio** [comment]
this is now supported using `invoice --to <address> <amount>`

**Comment by jaspervdm** [comment]
Are invoices always automatically accepted? Or is there a way to view the received invoices and accept/decline them.
