### ISSUE TITLE
 Compiling untrusted v0.6.2 error: Edition 2018 is unstable and only available

### ISSUE THREAD

**Issue by klugev303** [vault713/wallet713#47]
```
 Compiling untrusted v0.6.2
error: Edition 2018 is unstable and only available for nightly builds of rustc.

error: Could not compile `zeroize`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```
what he doesn't like?

**Comment by jaspervdm** [comment]
Run `rustup update`

**Comment by klugev303** [comment]
> rustup: command not found

  ((

**Comment by jaspervdm** [comment]
[wallet713 has the same requirements as Grin](https://github.com/mimblewimble/grin/blob/master/doc/build.md#requirements). The first requirement on that list is Rust, installed with `rustup`

**Comment by klugev303** [comment]
set clean _ubuntu-18.04.1-live-server-amd64_ and everything fell right, on 16.4 dont work, thanks
