### ISSUE TITLE
Grinbox federation support

### ISSUE THREAD

**Issue by ravidio** [vault713/wallet713#5]
Wallet713 to direct slates to different grinbox instances based on the domain part of the grinbox address. i.e. `send 1 --to xd56574...ffg@grinbox.io`. By default client would use the grinbox port 13420, however the port could be further specified in the address as well: `xd56574...ffg@grinbox.io:5555`

**Comment by ravidio** [comment]
support added

**Comment by lehnberg** [comment]
Where's the pull request? :)
