### ISSUE TITLE
--help always replies ERROR: ...

### ISSUE THREAD

**Issue by iljah** [vault713/wallet713#57]
In git clone from a few h ago, adding --help to any command always replies with ERROR: cmd as first line:

```
wallet713> accounts

____ Wallet Accounts ____

 Name    | Parent BIP-32 Derivation Path 
---------+-------------------------------
 default | m/0/0 

wallet713> accounts --help
ERROR: accounts 
lists available accounts

USAGE:
    accounts

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

```

also help command itself should support --help since that's listed:

```
wallet713> help
ERROR:  

USAGE:
     [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
...
wallet713> help --help
ERROR: error: The subcommand '--help' wasn't recognized

USAGE:
         help <subcommands>...

For more information try --help
```

**Comment by dasterdly** [comment]
did you follow the steps in setting up grin correctly? had the same issue when missing cargo build!

rust 1.31+ (use rustup- i.e. curl https://sh.rustup.rs -sSf | sh; source $HOME/.cargo/env)
if rust is already installed, you can simply update version with rustup update

git clone https://github.com/mimblewimble/grin.git
cd grin
cargo build --release

**Comment by iljah** [comment]
> rust 1.31+

I used rust and cargo that are in Fedora (28) repositories.

> git clone https://github.com/mimblewimble/grin.git
> cd grin
> cargo build --release

That's what I did, possibly with --recursive added to clone.

**Comment by dasterdly** [comment]
Lehnberg: what OS are you using? It must be a permission issue?

**Comment by lehnberg** [comment]
@dasterdly I'm on macOS as well. Just to be clear: --help still works, but it includes an ERROR: first.

**Comment by iljah** [comment]
In git checkout from few min ago, --help doesn't work for help itself:
```
wallet713> help --help
ERROR: error: The subcommand '--help' wasn't recognized

USAGE:
         help <subcommands>...

For more information try --help
```
even tough technically it should:
```
wallet713> help
ERROR:  

USAGE:
     [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information
```

**Comment by ravidio** [comment]
fixed with the recent commit.
