### ISSUE TITLE
Print grinbox address

### ISSUE THREAD

**Issue by iljah** [vault713/wallet713#58]
In git clone from few h ago, there doesn't seem to be any other way to see my (grinbox) address except to restart. Commands that sound like they would be helpful in this case don't show my address: account, accounts, info, contacts.

**Comment by lehnberg** [comment]
Adding the requirement that this command should also print the [index the current grinbox address is derived from](
https://github.com/vault713/wallet713/blob/master/docs/usage.md#switching-address).
