### ISSUE TITLE
Passphrase entry (plaintext visible in terminal)

### ISSUE THREAD

**Issue by antiochp** [vault713/wallet713#69]
* Passing passphrase directly to wallet713 via `-p <passphrase>` involves typing it (and seeing it) in the terminal
* Explicit `unlock` once in wallet713 involves typing and seeing the passphrase

It would be good to mask the passphrase when entering it.

* Allow `-p` to be passed in _without_ a passphrase and then prompt the user for the password and mask it.
* Allow `unlock` without a passphrase and then prompt the user for the passphrase and mask it.

Or am I missing something and this is already possible?

**Comment by jaspervdm** [comment]
I agree, we should add this. This would work well with the features suggested in https://github.com/vault713/wallet713/issues/9. Thanks for raising it!

**Comment by antiochp** [comment]
Yay!
