### ISSUE TITLE
Binary error while loading shared libraries: libssl.so.1.0.0

### ISSUE THREAD

**Issue by urza** [vault713/wallet713#78]
I downloaded the binary release, on Ubuntu 18.04 server, and on running ./wallet713 I got this error:

`./wallet713: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory`

**Comment by lehnberg** [comment]
https://github.com/vault713/wallet713/blob/master/docs/setup.md#requirements

Install open ssl

**Comment by theymos** [comment]
I think that there is in fact a bug in the build environment which is causing it to link against some really weird set of openssl versions. I suspect that the binary won't work on most platforms.

**Comment by Sharpiro** [comment]
Fedora currently uses openssl 1.1.1, as it is now the latest LTS and stable version, with no downgrade options.  I tried setting up symbolic links as usual, but I'm getting additional errors even after that.

```
./wallet713: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./wallet713)
./wallet713: /lib64/libcrypto.so.1.0.0: version `OPENSSL_1.0.2' not found (required by ./wallet713)
./wallet713: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.2' not found (required by ./wallet713)
./wallet713: /lib64/libssl.so.1.0.0: version `OPENSSL_1.0.0' not found (required by ./wallet713)
```

I was able to build 1.0.2 from source, but I don't know how to get rid of those errors.  Can we just update wallet713 to use openssl 1.1.1 as it seems like it should now be the standard?

**Comment by grigio** [comment]
Also in Debian

```
E: Package 'libssl1.0.0' has no installation candidate
```

**Comment by theymos** [comment]
I recommend building the official binary in a fresh Debian stable VM with only the minimal packages needed for the build.

**Comment by Sharpiro** [comment]
@grigio 
I've never really used docker, but I was able to build your docker file, but I can't seem to execute any commands.

i'm running:
```bash
# 'grinwallet713' is what I named the repo
sudo docker run grinwallet713
```

but it just returns immediately with no error

**Comment by grigio** [comment]
@Sharpiro try with:
`docker run --rm --name wallet713 -ti -v $PWD/data:/root/.wallet713 my/wallet713 wallet713`

**Comment by Sharpiro** [comment]
@grigio 
thanks, that command worked!

If you have some time i'd love an explanation on what that command is doing haha.

I read the docs for each one under ```docker run```, but I'd appreciate some more insight in how you knew those were necessary to get wallet713 functioning.

**Comment by grigio** [comment]
@Sharpiro it's a very simple command, it writes the important stuff in the local directory `data` and then it call the binary `wallet713`. You can also use `ctrl+p ctrl+q` to exit and resume the container.

@jaspervdm  would you accept a PR with the `Dockerfile` and the instructions ?

**Comment by jaspervdm** [comment]
Yes, i think having a Dockerfile is very useful

**Comment by ravidio** [comment]
This should be sorted out in v1.0.1 release.

**Comment by urza** [comment]
After downloading and running new binary release I got this error:

```
:~/wallet713$ ./wallet713
./wallet713: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
Press any key to continue...
```

I am on  Debian GNU/Linux 9.4 (stretch)
kernel 4.9.0-4-amd64

openssl version in debian is:
```
:~/wallet713$ apt-cache policy openssl
openssl:
  Installed: 1.1.0f-3+deb9u2
  Candidate: 1.1.0f-3+deb9u2
```

**Comment by urza** [comment]
Updated debian to latest version, but unfortunately no change for wallet713, the same error message.
```
debian  9.7
kernel 4.9.0-4-amd64
openssl: Installed: 1.1.0j-1~deb9
```u1

**Comment by jmliz** [comment]
Getting this error again on Fedora 29 for version 1.1.0.

**Comment by ASHERH4X** [comment]
Getting this error still.

**Comment by lehnberg** [comment]
I want to believe that we finally, once and for all, have put this issue to bed. 

Try the new streamlined download and install experience here:
https://wallet.713.mw/install

Let me know if it works. 🤺

**Comment by jmliz** [comment]
@lehnberg 

still not working

```
[user@pc ~]$ curl https://wallet.713.mw/install.sh -sSf | sh
\033[1;34mWallet713 binary installer 1.0\033[0m
\033[1;30m
Configuration: [amd64]
Location:      [https://github.com/vault713/wallet713/releases/download/v1.1.1/wallet713-v1.1.1-508990898-linux-amd64.tgz]
Directory:     [/home/user/bin]
\033[0m
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   633    0   633    0     0    909      0 --:--:-- --:--:-- --:--:--   908
100 5661k  100 5661k    0     0   208k      0  0:00:27  0:00:27 --:--:--  260k
\033[0;32m
Installation completed successfully.
$ wallet713 --version
/home/user/bin/wallet713: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
\nRun 'wallet713' from the command line to open the wallet
\033[0m
```
> Let me know if it works.

I don't know but I would expect you tested it and at least confirmed it works in a default distro install so I can expect something.

**Comment by lehnberg** [comment]
@jmliz thanks for reporting. We did indeed do several tests, but not on Fedora 29 specifically. Investigating.

**Comment by fueleh** [comment]
wallet713
wallet713: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
i got this problem when i updated to ubuntu 19.04.
i could build it so got it working that way.

**Comment by jaspervdm** [comment]
@urza @jmliz @fueleh Would you be willing to test out the [latest binary](https://github.com/vault713/wallet713/releases/tag/v1.1.1-test)? I think SSL error should be fixed now, finally.

**Comment by fueleh** [comment]
> @urza @jmliz @fueleh Would you be willing to test out the [latest binary](https://github.com/vault713/wallet713/releases/tag/v1.1.1-test)? I think SSL error should be fixed now, finally.

nope
curl https://wallet.713.mw/install.sh -sSf | sh
then
wallet713
wallet713: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by urza** [comment]
@jaspervdm

works fine for me on Ubuntu 18.04

I no longer have the debian box though..

**Comment by jaspervdm** [comment]
Given that we have received no new reports of broken binaries for a while, I am assuming the fixes we implemented some time ago were sufficient.
