### ISSUE TITLE
how to View the history of receive history and send history ？

### ISSUE THREAD

**Issue by mmelodious** [vault713/wallet713#83]
hi, i want to know how to View the history of receive history and send history ,beacuase i send someone 100 grin , and i can confirmed it is successful , but he say he have not accept this amount grin. thanks .

**Comment by mmelodious** [comment]
i only can know the shared transaction id by use "txs" command ,and the confirmed is true.

**Comment by ravidio** [comment]
Hi @mmelodious, with v1.0.1 as a sender you can generate proofs whenever you send someone grins via grinbox. Hopefully that helps with the issue you describe above. I'll close this issue but please let me know if you still require help here.

**Comment by trummax** [comment]
Hi @ravidio, does this method work to prove txs made in v1.0.0 wallet?

**Comment by lehnberg** [comment]
@trummax no, v1.0.1 is required unfortunately.
