### ISSUE TITLE
support receive grin with http ip option

### ISSUE THREAD

**Issue by wenqingyu** [vault713/wallet713#89]
### Background
There are some mining pools only offer to withdraw grin with HTTP IP rather than Grinbox backed hash address. 

### Propose feature
As a Wallet713 user, I'd like to receive Grin with HTTP IP option.

**Comment by bhakterija** [comment]
Same with hotbit.io exchange - seems it only supports http(s) deposits and withdrawals.

**Comment by ravidio** [comment]
Wallet713 v1.0.1 supports https. The reason we don’t do http is because it is prone to MITM attacks.

**Comment by bhakterija** [comment]
> Wallet713 v1.0.1 supports https. The reason we don’t do http is because it is prone to MITM attacks.

[Documentation](https://github.com/vault713/wallet713/blob/master/docs/usage.md#receiving-via-https) states that receiving via https is not yet supported. 
If https receiving is actually available in current version, can you please provide an example of the command?
Thanks!

**Comment by ravidio** [comment]
Sure, see in the doc the section: “Configuring Foreign and Owner APIs”. You need to have the foreign api configured for that to work. Thanks!

**Comment by ravidio** [comment]
@bhakterija, please note we have tweaked the docs following your comment! It now properly indicates that receiving via http is supported via the foreign API and provides more concrete instructions on how to set this up. Thanks a lot for pointing this out to us, and let me know if you experience any issues please.

**Comment by bhakterija** [comment]
> @bhakterija, please note we have tweaked the docs following your comment! It now properly indicates that receiving via http is supported via the foreign API and provides more concrete instructions on how to set this up. Thanks a lot for pointing this out to us, and let me know if you experience any issues please.

That worked perfectly, thank you!
