### ISSUE TITLE
Awaiting confirmation for over 40 blocks

### ISSUE THREAD

**Issue by iljah** [vault713/wallet713#93]
Used info command twice in git checkout of wallet from two days ago. First time it printed some balance as `Awaiting confirmation (< 10)` at height 9815 and second time it printed the same thing but at height 9858.  Isn't the transfer supposed to have confirmed already or am I misunderstanding something?

**Comment by iljah** [comment]
Or does this mean that those transactions are in mempool but haven't been included in any blocks yet? In that case, why imply that they've been included in chain with (< 10)?

**Comment by jaspervdm** [comment]
This probably means that the transaction hasn't been included in a block. You can view the number of confirmations of specific outputs with the `outputs` command.

While technically unconfirmed outputs do have <10 confirmations, I agree that it is not very clear. I will add a separate line for unconfirmed outputs. I believe the default grin wallet has the same display so I will also add it in there.

**Comment by iljah** [comment]
Thanks. I think bitcoin GUI doesn't add unconfirmed incoming transfers to total it shows but outgoing are substracted even with 0 confirmations. Separate line for unconfirmed transactions would be nice in any case.

**Comment by jaspervdm** [comment]
Latest version of the wallet has an "Awaiting finalization" entry which shows the total value of the outputs with 0 confirmations.
